name: "Build a Charm"
description: "Pack a charm with Charmcraft"
author: "Canonical"
inputs:
  path:
    description: >
      The location of the Charmcraft project. 
      
      Defaults to the base of the repository.
    default: '.'
  verbosity:
    description: >
      Set the build verbosity level to 'quiet', 'brief', 'verbose', 'debug' or
      'trace'.

      The default is 'trace'.
    default: 'trace'
  charmcraft-channel:
    description: >
      Install the snap from a specific channel

      If not provided, it defaults to stable.
    default: 'stable'
  revision:
    description: >
      Pin the snap revision to install.

      If not provided, it defaults to whatever revision is in latest/stable.
    default: ''
  cache-packages:
    description: >
      Set whether the action will save charmcraft's package build cache to
      the repository's cache.  See https://github.com/actions/cache for
      information on scoping.

      Must be set to "true" or "false".  If not provided, it defaults to true.
    default: 'true'
outputs:
  charm:
    description: 'The file name of the resulting Charm.'
runs:
  using: 'node20'
  main: '../dist/charmcraft-pack-action/index.js'
branding:
  icon: layers
  color: orange
